name: color_simp
description: A simple Dart package for demonstration.
version: 0.0.1
repository: https://github.com/mtndbs/color_simp

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.24.0 # For running tests
