name: color_simp
description: A simple Dart package that adds colorful console logging using ANSI escape codes.
version: 1.0.3
repository: https://github.com/mtndbs/color_simp

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.24.0 # For running tests
